
rules = [
  DisableSyntax
  LeakingImplicitClassVal
  NoValInForComprehension
  RemoveUnused
  OrganizeImports
]

OrganizeImports {
  targetDialect = Scala3
  groupedImports       = Keep
  groups               = ["re:javax?\\.", "scala.", "ice.", "*"]
  removeUnused         = true
  importSelectorsOrder = Keep
  importsOrder         = Keep
}

DisableSyntax {
  noVars = true
  noThrows = true
  noNulls = false
  noReturns = true
  noWhileLoops = false
  noAsInstanceOf = false
  noIsInstanceOf = true
  noDefaultArgs = false
  noFinalVal = true
  noFinalize = false
  noValPatterns = false
  noUniversalEquality = false
}
