syntax = "proto3";

package io.vangogiel.example.finance;

import "io/vangogiel/example/finance/create-account-request.proto";
import "io/vangogiel/example/finance/create-account-response.proto";
import "io/vangogiel/example/finance/deposit-money-request.proto";
import "io/vangogiel/example/finance/deposit-money-response.proto";
import "io/vangogiel/example/finance/withdraw-money-request.proto";
import "io/vangogiel/example/finance/withdraw-money-response.proto";
import "io/vangogiel/example/finance/transfer-money-request.proto";
import "io/vangogiel/example/finance/transfer-money-response.proto";
import "io/vangogiel/example/finance/account-balance-request.proto";
import "io/vangogiel/example/finance/account-balance-response.proto";

service FinanceService {
  rpc createAccount(CreateAccountRequest) returns (CreateAccountResponse);
  rpc depositMoney(DepositMoneyRequest) returns (DepositMoneyResponse);
  rpc withdrawMoney(WithdrawMoneyRequest) returns (WithdrawMoneyResponse);
  rpc transferMoney(TransferMoneyRequest) returns (TransferMoneyResponse);
  rpc getAccountBalance(AccountBalanceRequest) returns (AccountBalanceResponse);
}
